name: CI/CD Pipeline

on:
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt

      - name: Run tests
        run: |
          python -m pytest tests/

      - name: Train model
        run: |
          python model/train.py

      - name: Upload model to Render
        run: |
          # Aqui você pode adicionar um comando para enviar o modelo para o Render ou outro serviço de armazenamento
          # Exemplo: usar o AWS CLI para enviar o modelo para o S3
          aws s3 cp model/model.pth s3://seu-bucket/model.pth