name: CI/CD for Deep Learning

on:
  push:
    branches:
      - main
      - deploy  # Adicionado para facilitar testes

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Instalar dependências
        run: pip install -r api/requirements.txt

      - name: Treinar modelo
        run: python model/train.py

      - name: Salvar modelo treinado
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model/model.pth

  deploy:
    needs: train
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Instalar dependências
        run: pip install -r api/requirements.txt

      - name: Baixar modelo treinado
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: model/

      - name: Rodar API com FastAPI
        run: uvicorn api.main:app --host 0.0.0.0 --port 8000 &


